<form action="/page/process" method="post">
    <table style="width: 100%;">
        <tr>
            <td colspan="2"><input name="id" type="hidden" value=""></td>
        </tr>
        <tr>
            <td colspan="2"><input name="user_id" type="hidden" value=""></td>
        </tr>
        <tr>
            <td>url</td>
            <td><input name="url"  required="" type="text" value=""></td>
        </tr>
        <tr>
            <td>title</td>
            <td><input name="title" required="" type="text" value=""></td>
        </tr>
        <tr>
            <td>index</td>
            <td><input name="index" required="" type="text" value=""></td>
        </tr>

        <tr>
            <td colspan="2"><textarea name="body"></textarea></td>
        </tr>        
        <tr>
            <td colspan="2"><input name="submit" type="submit" value="save"></td>
        </tr>

    </table>

</form>

<script src="/js/ckeditor_full/ckeditor.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        CKEDITOR.replace('body');
    });
</script>



