<style>
    .feedback-form {

    }
    .feedback-form dt,
    .feedback-form dd {
        line-height: 12px;

    }
    .feedback-form dt {
        margin: 10px 0px 2px 0px;
    }
</style>


<form class="feedback-form">
    <dl>
        <dt>Ваше имя</dt>
        <dd><input class="name" required="true" type="text" name="name" style="width: 300px;"></dd>

        <dt>Контакты</dt>
        <dd><textarea  class="contacts" required="true" type="text" name="contacts" placeholder="" style="width: 300px;"></textarea></dd>

        <dt>Сообщение</dt>
        <dd><textarea class="message" required="true" type="text" name="message" placeholder="" style="width: 300px;"></textarea></dd>

        <?php
        $form = new \Page\Form\FeedbackForm();
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>

        <dd class="figlet_captcha">
            <?= $this->formCaptcha($form->get('captcha')); ?>
            <span class="errors"><?= $this->formElementErrors($form->get('captcha')); ?></span>
        </dd>

        <?= $this->form()->closeTag(); ?>

        <dt>&nbsp;</dt>
        <dd><input  class="submit" type="button" value="Отправить"></dd

        <dt><div class="success">Сообщение успешно отправлено.</div></dt>
        <dt><div class="errorcap">Ошибка. Не верно введена капча.</div></dt>
        <dt><div class="error">Ошибка. Пожалуйста, заполните всё поля.</div></dt>
    </dl>
</form>




<style>
    .feedback-form {
        margin: 0 auto;
    }
    .feedback-form dl dt {
        color: #828282;
        font-size: 12px;
        line-height: 14px;
        margin-bottom: 2px;
        margin-top: 10px;
    }
    .feedback-form textarea {
        height: 70px;
    }

    .page-module #content form {
        width: 300px;
    } 
    page-module #content form dt {
        margin-top: 10px;
    }
    .page-module #content form dd,
    .page-module #content form dt
    {
        width: 300px;
    }

    .page-module #content form input,
    .page-module #content form textarea {
        width: 300px;
        max-width: 300px;
        margin: 0px;
        padding: 0px 5px !important;
        box-sizing: border-box;
    }
    .page-module #content form .submit {
        display: block;
        text-align: center;
        color: #fff;
        width: 90px;
        height: 25px;
        line-height: 23px;
        background: #009cff;
        margin: 0 auto;
        cursor: pointer;
        border-style: none;
    }
    .page-module #content form .success { 
        display: none;
        border: 1px solid #5cb85c;
        color: #5cb85c;
        padding: 5px;
        margin: 20px 0px;
    }

    .page-module #content form .error { 
        display: none;
        border: 1px solid red;
        color: red;
        padding: 5px;
        margin: 20px 0px;
    }

    .page-module #content form .errorcap { 
        display: none;
        border: 1px solid red;
        color: red;
        padding: 5px;
        margin: 20px 0px;
    }

</style>

<script>
    $(document).ready(function() {
        $('.submit').on('click', function(e) {

            var data = new FormData();
            data.append('name', $('.name').val());
            data.append('contacts', $('.contacts').val());
            data.append('message', $('.message').val());
            data.append('captcha[id]', $('input[name="captcha[id]"]').val());
            data.append('captcha[input]', $('input[name="captcha[input]"]').val());


            if ($('.name').val() === '' || $('.contacts').val() === '' || $('.message').val() === '' || $('.captcha').val() === '') {
                $('.error').show();
                $('.errorcap').hide();
                $('.success').hide();
                setTimeout(function() {
                    $('.error').hide();
                }, 1800);
            } else {

                $.ajax({
                    type: "POST",
                    url: "/page/json-feedback",
                    data: data,
                    cache: false,
                    processData: false,
                    contentType: false,
                    success: function(response) {
                        if (response && response.status === 'ok') {
                            $('.name').val("");
                            $('.contacts').val('');
                            $('.message').val('');
                            $('.captcha').val('');
                            $('.success').show();
                            $('.error').hide();
                            $('.errorcap').hide();
                            setTimeout(function() {
                                $('.success').hide();
                                location.reload();
                            }, 1800);
                        } else {
                            $('.errorcap').show();
                            $('.success').hide();
                            setTimeout(function() {
                                $('.errorcap').hide();
                            }, 1800);
                        }
                    }
                });
            }
        });
    });
</script>


