<?php
//

$sm = $this->getServiceManager();
$pageTable = $sm->get('page_table');
$pages = $pageTable->fetchAll();

//
?>
<style>
    body.page-module #vip-ads
    {
        display: none;
    }
    body.page-module #content table  {
        width: 810px;
        margin-bottom: -1px;
    }
    body.page-module #content table a {
        color: #009cff;
    }
    body.page-module #content table a:hover {
        text-decoration: underline;
    }
    body.page-module #content  {
        width: 810px;
        font-family: 'Courier New';
    }
    body.page-module #content table td,
    body.page-module #content table th
    {
        border:1px solid #ccc;
        font-size: 14px;
        line-height: 16px;
        padding: 5px;
    }
    .page-module .add-page {
        display: block;
        margin: 10px 10px;
        color: #009cff;
    }
</style>
<a class="add-page" href="<?php echo '/page/add'; ?>">Добавить страницу</a>
<table border="1">
    <tr>
        <th>id</th>
        <!--<th>user_id</th>-->
        <th>title</th>
        <th>url</th>
        <!--<th>body</th>-->
        <th>index</th>
        <!--<th>create_date</th>-->
        <th>Действия</th>
    </tr>
    <?php foreach ($pages as $page) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($page->id); ?></td>
            <!--<td><?php echo $this->escapeHtml($page->user_id); ?></td>-->
            <td><?php echo $this->escapeHtml($page->title); ?></td>
            <td><?php echo $this->escapeHtml($page->url); ?></td>
            <!--<td><?php //echo $this->escapeHtml($page->body);         ?></td>-->
            <td><?php echo $this->escapeHtml($page->index); ?></td>
          <!--<td><?php echo $this->escapeHtml($page->create_date); ?></td>-->
            <td>
                <a href="<?php echo '/page/view/' . $this->escapeHtml($page->url); ?>">просмотреть</a><br/>
                <a href="<?php echo '/page/edit/' . $this->escapeHtml($page->url); ?>">редактировать</a><br/>
                <a href="<?php echo '/page/delete/' . $this->escapeHtml($page->url); ?>">удалить</a><br/>
            </td>
        </tr>

    <?php endforeach; ?>
</table>
