<?php
//

$sm = $this->getServiceManager();
$pageTable = $sm->get('page_table');

try {
    $page = $pageTable->getPageByUrl($url);
//
    ?>

    <div class="page-body">

        <div class="page-title" data-id="<?= $page->id ?>" data-url="<?= $page->url ?>">
            <h2><?php echo $page->title; ?> 
                <?php if ($sm->get('logged_in_user')->role_id == 3) : ?>
                    <a class="page-edit-link" href="/page/edit/<?= $page->url; ?>">Редактировать</a>
                <?php endif; ?>
            </h2>

        </div>

        <div class="page-text">
            <?php
            if ($page->url == 'feedback') {
                include 'feedback.phtml';
            } else {
                echo $page->body;
            }
            ?>

        </div>
    </div>
    <?php
} catch (Exception $exc) {
    ?>
    <div class="page-body">
        <div class="page-title"><h2>Ошибка 404 - Страница не найдена</h2></div>
        <div class="page-text"></div>
    </div>

    <?php
}
?>

<style>
    body.page-module .top_line {
        width: 810px;
    }
    body.page-module #vip-ads
    {
        display: none;
    }
    body.page-module #content table
    {
        width: 643px;
    }
    body.page-module #content,  body.page #content .top_line
    {
        width: 810px;
    }
    .page-body .page-text {
        font-size: 14px;
        padding: 5px 0px;
        line-height: 16px;
    }
    .page-body .page-title {
        padding: 10px;
        border-bottom: 1px solid #dbdbdb;
    }
    .page-body .page-edit-link {
        color: #009cff;
        font-size: 10px;
    }
    .page-body p {
        margin: 0px 0px 7px;
    }
    .page-body ul {
        list-style: disc;
        list-style-type: disc !important;
        padding: 0 0 0 40px;

    }
</style>

<?php $this->headScript()->appendFile($this->basePath()."/js/jquery.tosrus.min.all.js", 'text/javascript');?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/jquery.tosrus.all.css');?>

<div id="links">
</div>

<script>
    $(document).ready(function() {
        $('.images').on('click', function() {
            $('#links').empty();
            var links = $("#links");
            //links.append($('<a></a>').attr('href', $(this).css('background-image').replace('url(', '').replace(')', '')));
            $('.images').each(function(index) {
                links.append($('<a></a>').attr('href', $(this).attr('src')));
            });

            $("#links a").tosrus({
                pagination: {
                    add: true,
                    type: "thumbnails"
                }
            });
            $('#links a:first').click();
        });
    });
</script>
