<?php
$form = $this->form;
$form->prepare();
?>

<div class="widget">
    <div class="widget-title"> 
        post edit widget <?php echo '[p:' . $post->get('post_id') . ']'; ?>
    </div>
    <div class="widget-body">

        <div class="view-link item">
            <a href="/post/view/<?= $post->get('post_id'); ?>">view</a>
        </div>

        <div class="item">
            <?php echo $this->formWidget($this->form); ?>
        </div>

    </div>
</div>