<div class="widget">
    <div class="widget-title"> 
        excerpt post view widget
    </div>
    <div class="widget-body">
        <div class="author">
            author <a href="/post/search/?user_id=<?= $post->get('user_id'); ?>"><?php echo '[u:' . $post->get('user_id') . ']'; ?></a>
        </div>
        <div class="title">
            title: <?= $post->get('title'); ?>
        </div>
        <div class="post">
            <div class="text"><?= 'text: ' . $post->get('text'); ?></div>
        </div>
    </div>
</div>