<div class="widget">
    <div class="widget-title"> 
        post preview widget <?php echo '[p:' . $post->get('post_id') . ']'; ?>
    </div>
    <div class="widget-body">
        <div class="author">
            author <a href="/post/search/?user_id=<?= $post->get('user_id'); ?>"><?php echo '[u:' . $post->get('user_id') . ']'; ?></a>
        </div>
        <div class="title">
            title: <?= $post->get('title'); ?>
        </div>
        <div class="text">
            <?= 'text: ' . $post->get('text'); ?>
        </div>
        <div class="view-link">
            <a href="/post/view/<?= $post->get('post_id'); ?>">view</a>
        </div>
    </div>
</div>