<div class="widget">
    <div class="widget-title"> 
        post view widget <?php echo '[p:' . $post->get('post_id') . ']'; ?>

        <div class="actions" style="float:right;">
            <?php if ($post->get('user_id') == $sm->get('logged_in_user_id')) : ?>
                <a href="/post/edit/<?php echo $post->get(\Post\Model\Post::POST_ID); ?>">edit</a>
                <a href="/post/delete/<?php echo $post->get(\Post\Model\Post::POST_ID); ?>">del</a>
            <?php endif; ?>
        </div>

    </div>
    <div class="widget-body">
        <div class="author">
            author <a href="/post/search/?user_id=<?= $post->get('user_id'); ?>"><?php echo '[u:' . $post->get('user_id') . ']'; ?></a>
        </div>
        <div class="title">
            title: <?= $post->get('title'); ?>
        </div>
        <div class="text">
            <?= 'text: ' . $post->get('text'); ?>
        </div>
        <div class="public">
            <?= 'public: ' . $post->get('public'); ?>
        </div>
    </div>
</div>