<?php
/* HARDCODE RULEZZ */

use Banners\Model\Banner;

$sm = $this->getServiceManager();
$userTable = $sm->get('users_table');
$user = $this->identity();
$isUserLoggedIn = isset($user) ? TRUE : FALSE;


// BANNERS
$bannersTable = $sm->get('banners_table');
$uploadsTable = $sm->get('uploads_table');

// SIMPLE BANNER
$simpleBannersImage = array();
$simpleBanners = array();
$simpleBannersSet = $bannersTable->getRandomBannersByTypeLimit(Banner::SIMPLE_BANNER, 3);

foreach ($simpleBannersSet as $simpleBanner) {
    array_push($simpleBanners, $simpleBanner);

    $simpleBannerImage = $uploadsTable->getUploadById($simpleBanner->image_id);
    if ($simpleBannerImage) {
        array_push($simpleBannersImage, $simpleBannerImage);
    } else {
        array_push($simpleBannersImage, new \Upload\Model\Upload());
    }
}

// SALE BANNER
$saleBanners = array();
$saleBannersImage = array();
for ($i = 0; $i < 1; $i++) {
    $saleBanner = $bannersTable->getRandomBannerByType(Banner::SALE_BANNER);
    if (!empty($saleBanner)) {
        $saleBanners[$i] = $bannersTable->getRandomBannerByType(Banner::SALE_BANNER);

        $saleBannerImage = $uploadsTable->getUploadById($saleBanners[$i]->image_id);
        if ($saleBannerImage) {
            array_push($saleBannersImage, $saleBannerImage);
        } else {
            array_push($saleBannersImage, new \Upload\Model\Upload());
        }
    }
}

//LOGO BANNER
$logoBanners = array();
$logoBannersImage = array();
$logoBannersSet = $bannersTable->getRandomBannersByTypeLimit(Banner::LOGO_BANNER, 10);

foreach ($logoBannersSet as $logoBanner) {
    array_push($logoBanners, $logoBanner);

    $logoBannerImage = $uploadsTable->getUploadById($logoBanner->image_id);
    if ($logoBannerImage) {
        array_push($logoBannersImage, $logoBannerImage);
    } else {
        array_push($logoBannersImage, new \Upload\Model\Upload());
    }
}

//VIP BANNER
$vipBanners = array();
$vipBannersImage = array();
$vipBannersSet = $bannersTable->getRandomBannersByTypeLimit(Banner::VIP_BANNER, 2);

foreach ($vipBannersSet as $vipBanner) {
    array_push($vipBanners, $vipBanner);

    $vipBannerImage = $uploadsTable->getUploadById($vipBanner->image_id);
    if ($vipBannerImage) {
        array_push($vipBannersImage, $vipBannerImage);
    } else {
        array_push($vipBannersImage, new \Upload\Model\Upload());
    }
}
?>

<?php // IF $TYPE = SIMPLE_BANNER ECHO HTML BELOW **************************     ?>
<?php if ($type == Banner::SIMPLE_BANNER) : ?>

    <style>
        .banner {
            background-position: center center;
            background-repeat: no-repeat;
            background-size: cover;
            cursor: pointer;
        }
    </style>

    <div class="container">

        <div class="wrap">
            <?php if (sizeof($simpleBannersImage) > 0) : ?>
                <?php $id = $simpleBanners[0]->user_id; ?>
                <?php $src = $simpleBannersImage[0]->getFilepath(); ?>
                <div class="banner simple" data-user-id="<?= $id; ?>" style="background-image: url('<?= $this->thumb($src, 170, 160); ?>');"></div>
            <?php endif; ?>
        </div>

        <div class="wrap">
            <?php if (sizeof($saleBannersImage) > 0) : ?>
                <?php $id = $saleBanners[0]->user_id; ?>
                <?php $src = $saleBannersImage[0]->getFilepath(); ?>
                <div class="banner sale" data-user-id="<?= $id; ?>" style="background-image: url('<?= $this->thumb($src, 170, 160); ?>');">
                    <p class="sales">СКИДКИ</p>
                    <p class="percent"><?= $saleBanners[0]->sale; ?>%</p>
                </div>
            <?php endif; ?>
        </div>

        <div class="wrap">
            <?php if (sizeof($simpleBannersImage) > 1) : ?>
                <?php $id = $simpleBanners[1]->user_id; ?>
                <?php $src = $simpleBannersImage[1]->getFilepath(); ?>
                <div class="simple banner" data-user-id="<?= $id; ?>" style="background-image: url('<?= $this->thumb($src, 170, 160); ?>');"></div>
            <?php endif; ?>
        </div>

        <div class="wrap">
            <?php if (sizeof($simpleBannersImage) > 2) : ?>
                <?php $id = $simpleBanners[2]->user_id; ?>
                <?php $src = $simpleBannersImage[2]->getFilepath(); ?>
                <div class="simple banner" data-user-id="<?= $id; ?>" style="background-image: url('<?= $this->thumb($src, 170, 160); ?>');"></div>
            <?php endif; ?>
        </div>

    </div>

<?php endif; ?>

<?php // IF $TYPE = LOGO_BANNER ECHO HTML BELOW ****************************    ?>
<?php if ($type == Banner::LOGO_BANNER) : ?>
    <style>
        #ads-slider .slider li div {
            position: relative;
            width: 145px;
            height: 35px;
            margin: 0px 2px; 
            background-position: center center;
            background-size: cover;
        }
    </style>

    <div class="wrap">
        <div id="slider1" class="slider">
            <ul style="">
                <?php for ($i = 0; $i < count($logoBanners); $i++) : ?>
                    <?php $id = $logoBanners[$i]->user_id; ?>
                    <?php $src = $logoBannersImage[$i]->getFilepath(); ?>
                    <li class="banner logo" data-user-id="<?= $id; ?>" onclick="window.location.href = '/post/list/<?= $id; ?>'">
                        <div style="background-image: url('<?= $this->thumb($src, 145, 35); ?>');"></div>
                    </li>
                <?php endfor; ?>
            </ul>

        </div>
        <div class="controls">
            <a href="#" class="prev-slide">&nbsp;</a> 
            <a href="#" class="next-slide">&nbsp;</a> 
        </div>
        <script src="/js/lemmon-slider.js"></script>
        <script>
                    $(document).ready(function() {
                        $('body .banner').on('click', function() {
                            var id = $(this).data('user-id');
                            window.location.href = '/post/list/' + id;
                        });
                    });

                    window.onload = function() {

                        // slider 1
                        $('#slider1').lemmonSlider({
                           infinite: true
                        });
                    }
                    //---------------------------------
                    sliderAutoplay();

                    $('#slider1-play').click(function() {
                        if (sliderTimeout == null) {
                            sliderAutoplay();
                        }
                        return false;
                    });

                    $('#slider1-pause').click(function() {
                        clearTimeout(sliderTimeout);
                        sliderTimeout = null;
                        return false;
                    });
                    //--------------------------------------------------

                    // slider autoplay function
                    // autoplay
                    var sliderTimeout = null;
                    function sliderAutoplay() {

                        $('#slider1').trigger('nextSlide');
                        sliderTimeout = setTimeout('sliderAutoplay()', 4000);

                    }
                    // pause slider function
                    function sliderPause() {
                        clearTimeout(sliderTimeout);
                    }

        </script>

        <style type="text/css" media="screen">
            body div.slider    { 
                overflow: hidden;
                position: relative;
                width: 1174px;
                margin: 0px auto;
                height: 35px !important; }
            body div.slider ul { margin:0; padding:0; height:45px; }
            body div.slider li { float:left; list-style:none; margin:0 5px 0 0; }
            body div.slider li { text-align:center; line-height:160px; font-size:25px; }
        </style>
    </div>

<?php endif; ?>

<?php // IF $TYPE = LOGO_BANNER ECHO HTML BELOW ****************************    ?>
<?php if ($type == Banner::VIP_BANNER) : ?>
    <style>
        #vip-ads .banner.vip {
            display: block;
            width: 138px;
            height: 180px;
            margin-bottom: 16px;
            border: 1px solid #dadada;
            font-size: 14px;
        }
        #vip-ads .banner.vip .image {
            width: 115px;
            height: 110px;
            margin: 12px 12px 2px 12px;

        }
    </style>

    <div class="container">
        <div class="wrap">
            <?php if (sizeof($vipBannersImage) > 0) : ?>
                <?php $id = $vipBanners[0]->user_id; ?>
                <?php $src = $vipBannersImage[0]->getFilepath(); ?>
                <?php $title = $vipBanners[0]->title; ?>
                <?php $cost = $vipBanners[0]->cost; ?>

                <div class="banner vip" data-user-id="<?= $id; ?>" >
                    <div class="image banner" style="background-image: url('<?= $this->thumb($src, 115, 110); ?>');"></div>
                    <div class="vip-label">VIP-объявление</div>
                    <div class="title"><span class="text_"><?= $title; ?> </span><span class="price"><?= !empty($cost) ? $cost . ' у.е.' : ''; ?></span></div>
                </div>
            <?php endif; ?>
        </div>

        <div class="wrap">
            <?php if (sizeof($vipBannersImage) > 1) : ?>
                <?php $id = $vipBanners[1]->user_id; ?>
                <?php $src = $vipBannersImage[1]->getFilepath(); ?>
                <?php $title = $vipBanners[1]->title; ?>
                <?php $cost = $vipBanners[1]->cost; ?>

                <div class="banner vip" data-user-id="<?= $id; ?>" >
                    <div class="image banner" style="background-image: url('<?= $this->thumb($src, 115, 110); ?>');"></div>
                    <div class="vip-label">VIP-объявление</div>
                    <div class="title"><span class="text_"><?= $title; ?> </span><span class="price"><?= !empty($cost) ? $cost . ' у.е.' : ''; ?></span></div>
                </div>
            <?php endif; ?>
        </div>
    </div>	
<?php endif; ?>

