<?php

use \Upload\Model\Upload; ?>

<div class="widget">

    <div class="widget-title"><h3>Attachment Add Widget</h3></div>

    <div class="widget-body">
        
        <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', "/attachment/process/$postId");
        ?>

        <?php echo $this->form()->openTag($form); ?>
        <div class="form-list">
            <?php foreach ($form as $element) : ?>
                <div class="<?php echo 'block-' . $element->getName(); ?>">
                    <div class="label"><?php echo $this->formLabel($element); ?></div>
                    <div class="error"><?php echo $this->formElementErrors($element); ?></div>
                    <div class="field"><?php echo $this->formElement($element); ?></div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php echo $this->form()->closeTag() ?>


    </div>

</div>