<?php
if (isset($userId)) {
    ?>
    Введите новый пароль<br/>
    <form method="post" action="/users/auth/change-process">
        <input type="hidden" name="key" value="<?php echo $key; ?>">
        <input type="hidden" name="userId" value="<?php echo $userId; ?>">
        <input required type="password" name="newPassword" value="" autocomplete="off">
        <input type="submit" name="sendForm" value="Принять">
    </form>

    <?php
} else {
    echo 'Ссылка не действительна. <br/>Воспользуйтесь функцией восстановления пароля повторно.';
}
?>