<?php
$imageUrl = (!empty($banner->image)) ? $banner->image : '/img/170x160_load.jpg';
?>

<style>

</style>

<table class="load-image" cellpadding="0" cellspacing="0">
    <tr>
        <td> 
            <div class="input-file" style="background-image: url(<?php echo $imageUrl; ?>); background-color: <?php if (!empty($imageUrl)) echo '#fff'; ?>;">
                <input name="file" class="file" type="file" value="">
            </div>
        </td>
    </tr>
</table>

<form class="form" method="post" enctype="multipart/form-data" action="/banners/simple/process">

    <input type="hidden" name="id" class="id" value="<?php echo $banner->id; ?>">
    <input type="hidden" name="user_id" class="user_id" value="<?php echo $banner->user_id; ?>">
    <input type="hidden" name="image_id" class="image_id" value="<?php echo $banner->image_id; ?>">
    <input type="hidden" name="image" class="image" value="<?php echo $banner->image; ?>">

    <table cellpadding="0" cellspacing="0">
        <tr>
            <td colspan="2"><p>Загрузите изрбражение разрешением 170х160 пикселей.</p></td>
        </tr>

        <tr>
            <td colspan="2"><input class="submit" type="submit" name="submit" value="Сохранить"></td>
        </tr>
    </table>

</form>


<script>
    $(document).ready(function() {

        $('.file').on('change', function(e) {

            var data = new FormData();
            var file = $('.file')[0].files[0];
            data.append('file', file);
            data.append('type', 1);
            data.append('id', $('.id').attr('value'));

            $.ajax({
                type: "POST",
                url: '/banners/simple/ajax-process',
                data: data,
                cache: false,
                processData: false,
                contentType: false,
                success: function(response) {
                    if (response && response.status === 'ok') {
                        var imageSrc = "/scripts/timthumb/timthumb.php?src=" + response.src + "&w=170&h=160";

                        $('.id').attr('value', response.id);
                        $('.image_id').attr('value', response.image_id);
                        $('.input-file').css('background-image', 'url(' + imageSrc + ')');
                        $('input[name="image"]').attr('value', imageSrc);
                    }
                }
            });
        });
    });
</script>

