<?php

use Banners\Model\Banner;

$sm = $this->getServiceManager();
$user = $sm->get('logged_in_user');
$bannersTable = $sm->get('banners_table');
$banners = $bannersTable->getBannersByTypeForUser(Banner::SIMPLE_BANNER, $user->getId());

$uploadsTable = $sm->get('uploads_table');
$simpleBanner_1 = $bannersTable->getRandomBannerByType(Banner::SIMPLE_BANNER);
$simpleBanner_2 = $bannersTable->getRandomBannerByType(Banner::SIMPLE_BANNER);
$simpleBanner_3 = $bannersTable->getRandomBannerByType(Banner::SIMPLE_BANNER);
?>


<div style="background: url('<?php ?>'); "><?php echo $simpleBanner_1->id; ?></div>
<div style="background: url('<?php ?>'); "><?php echo $simpleBanner_2->id; ?></div>
<div style="background: url('<?php ?>'); "><?php echo $simpleBanner_3->id; ?></div>

<?php echo 'Simple banners list'; ?>
<a href="/banners/simple/add">add</a>
<table cellpadding="0" cellspacing="0">
    <tr>
        <th>id</th>
        <th>user_id</th>
        <th>image_id</th>
        <th>type</th>
        <th>url</th>
        <th>title</th>
        <th>cost</th>
        <th>sale</th>
        <th>create_date</th> 
        <th>off_date</th> 
        <th>is_on</th> 
    </tr>
    <?php foreach ($banners as $banner) : ?> 
        <tr>
            <td><?= $banner->id ?></td>
            <td><?= $banner->user_id ?></td>
            <td><?= $banner->image_id ?></td>
            <td><?= $banner->type ?></td>
            <td><?= $banner->url ?></td>
            <td><?= $banner->title ?></td>
            <td><?= $banner->cost ?></td>
            <td><?= $banner->sale ?></td>
            <td><?= $banner->create_date ?></td>
            <td><?= $banner->off_date ?></td>
            <td><?= $banner->is_on ?></td>
        </tr>
    <?php endforeach; ?>
</table>


<style>
    table, td, th {
        border: 1px solid seagreen;
        padding: 5px;
    }
    th {
        font-weight: bold;
    }
</style>