<?php
$sm = $this->getServiceManager();
$userTable = $sm->get('users_table');
$loggedInUser = $sm->get('logged_in_user');
//
?>


<?php
if ($this->dialogs->count()) {
    foreach ($this->dialogs as $dialog):
        ?> 

        <?php
        // get users id
        $loggedInUserId = $loggedInUser->user_id;

        if ($loggedInUserId == $dialog->sender_id) {
            $selectedUserId = $dialog->recipient_id;
        } else {
            $selectedUserId = $dialog->sender_id;
        }
        $selectedUser = $userTable->getUser($selectedUserId);

        // check: is message new to set background
        $is_new_line = null;
        $is_new_sub_line = null;
        if ($dialog->is_new) {
            if ($loggedInUserId !== $dialog->sender_id) {
                $is_new_line = 'is_new';
            } else {
                $is_new_sub_line = 'is_new';
            }
        }

        // set private dialog link
        $chatUrl = ($loggedInUser->getId() == $dialog->sender_id) ?
                '/dialog/open/' . $dialog->recipient_id :
                '/dialog/open/' . $dialog->sender_id;
        $sender = $userTable->getUser($dialog->sender_id);
        ?>

        <table class="line item <?= $is_new_line; ?>" cellpadding="0" cellspacing="0" onclick="window.location = '<?php echo $chatUrl; ?>'">
            <tr>
                <td rowspan="2">
                    <div class="delete_block">
                        <a class="delete icon" href="/dialog/delete/<?= $selectedUserId ?>"></a>
                    </div>
                </td>
                <?php
                $userData = $this->getUserData($selectedUserId);
                $avatar_url = $userData->getAvatarUrl();
                ?>
                <td rowspan="2"><div class="sender_image" style="background-image: url('<?php echo $this->thumb($avatar_url, 37, 37); ?>'); width: 37px; height: 37px;"></div></td>
                <td colspan="2"><span class="sender"><?php echo $this->escapeHtml($selectedUser->display_name); ?></span></td>
                <td rowspan="2"><div class="date">
                        <?php
                        $dialogCreateDate = $dialog->create_date;
                        $dialogDate = new DateTime($dialogCreateDate);
                        $formatedDialogDate = date_format($dialogDate, 'd.m.y H:i');
                        ?>
        <?php echo $this->escapeHtml($formatedDialogDate); ?>
                    </div></td>
            </tr>
            <tr>
                <td class="last-sender-ava-block">
                    <?php if ($loggedInUserId == $dialog->sender_id) : ?>
                        <div class="last-sender-ava" style="background-image: url('<?php echo $this->thumb($this->getUserData($loggedInUserId)->getAvatarUrl(), 17, 17); ?>');"></div>
        <?php endif; ?>
                </td>
                <td class="text-block"><div class="text <?= $is_new_sub_line; ?>"><?php echo $this->escapeHtml($dialog->text); ?></div></td>
            </tr>
        </table>

    <?php endforeach; ?>

<?php } else { ?>
    <div class="no-posts-favorites-dialogs">Нет сообщений</div>
<?php }
?>
