<?php
$form = $this->form;
$form->prepare();
?>

<?php echo $this->form()->openTag($form); ?>
<div class="form-list">
    <?php $index = 0; ?>
    <?php foreach ($form as $element) : ?>
        <div class="form-list-item-<?php echo ++$index . ' field-' . $element->getName(); ?>">
            <div class="title"><?php echo $this->formLabel($element); ?></div>
            <div class="error"><?php echo $this->formElementErrors($element); ?></div>
            <div class="field"><?php echo $this->formElement($element); ?></div>
        </div>
    <?php endforeach; ?>
</div>
<?php echo $this->form()->closeTag() ?>