<?php
//
$sm = $this->getServiceManager();
//
?>
<style>
    
</style>
<div class="post-details">
    <div class="single-post item" data-id ="<?= $post->getId() ?>">

        <div class="post-avatar">
            <?php
            //
            $postUserId = $this->post->user_id;
            $postUserData = $this->getUserData($postUserId);
            $postLink = "/post/details/$post->id";
            $userLink = "/post/list/$postUserId";
            //
            ?>
            <a href="<?= $userLink; ?>">
                <div style="background-image: url(<?php echo $postUserData->getAvatarUrl(); ?>);"></div>
            </a></div>

        <div class="post-actions">
            <?php $loggedInUser = $sm->get('logged_in_user'); ?>
            <?php if (isset($loggedInUser->user_id)) : ?>

                <?php if ($loggedInUser->user_id == $post->getUserId()) : ?>
                    <div class="edit" onclick="window.document.location = '/post/edit/<?php echo $post->getId(); ?>'"></div>
                    <div class="divide">|</div>
                    <div class="refresh"></div>
                    <div class="divide">|</div>
                    <div class="delete" data-post-id="<?php echo $post->getId(); ?>"></div>
                <?php else : ?>
                    <div class="chat" onclick="window.document.location = '/dialog/open/<?php echo $post->getUserId(); ?>'"></div>
                <?php endif; ?>

            <?php endif; ?>
        </div>


        <?php
        $author = $sm->get('users_table')->getUserById($this->post->user_id);
        $at = $sm->get('attachment_table');
        $files = $at->fetchAllByPostId($post->getId());
        $images = $at->getImagesByPostId($post->getId());

        $cityLocation = \Catalog\Data\Location::getLocationNameById($post->city);

        $postCreateDate = $post->getCreateDate();
        $postDate = new DateTime($postCreateDate);
        $formatedPostDate = date_format($postDate, 'd.m.y H:i');

        $postChaffer = ($post->chaffer) ? 'Договорная ' : '';
        ?>
        <div class="post-body">

            <div class="post-auhtor">
                <a href="/post/list/<?= $author->user_id; ?>">
                    <?php echo $author->display_name; ?>
                </a>

            </div>

            <div class="wrap">
                <div class="post-location">
                    <?php echo $cityLocation; ?>

                </div>
                <div class="post-create-date">
                    <?php echo $formatedPostDate; ?>
                </div>
                <div class="post-chaffer">
                    <?php echo $postChaffer; ?>
                </div>
                <div class="post-price firm_red">
                    <?php echo isset($post->price) ? $this->escapeHtml($post->price) . ' у.е.' : ''; ?> 
                </div>
            </div>

            <div class="wrap">
                <div class="post-title"><p><?= $post->getTitle(); ?></p></div>
            </div>

            <div class="post-text"><?= nl2br($this->escapeHtml($this->post->getText())); ?></div>
            <div class="tags"> 
                <?php
                
                preg_match_all('/#[^\\s#]+/', $post->tags, $matches);
                if (count($matches[0])) { 
                    for ($i=0; $i<count($matches[0]); $i++) {?>
                   <?php $a = substr($matches[0][$i], 1);?>
                <a href="/post/tags?t=<?=$a; ?>"><?=$matches[0][$i];?></a>
                    <?php  }
                }
                ?>
            </div>

            <div class="wrap-images">
                <div class="images">
                    <?php
                    $imagesCount = $images->count();
                    $imagesArray = $images->toArray();
                    ?>

                    <?php if ($imagesCount == 0) : ?>
                        <div class="big_img" data-src="/img/358x238_none.jpg" style="background-image: url('/img/358x238_none.jpg'); border: 1px solid #dbdbdb;"></div>
                    <?php endif; ?>

                    <?php if ($imagesCount > 0) : $src = $this->uploadfilemanager->getFilePath($imagesArray[0]['upload_id']); ?>
                        <div class="big_img" data-src="<?php echo $src; ?>" style="background-image: url('<?php echo $this->thumb($src, 358, 238); ?>')"></div>
                    <?php endif; ?>

                    <?php if ($imagesCount > 1) : ?>
                        <div class="small_imgs">
                            <?php for ($i = 1; $i < $imagesCount; $i++) : $src = $this->uploadfilemanager->getFilePath($imagesArray[$i]['upload_id']); ?>
                            <div class="small_img" data-src="<?php echo $src; ?>" style="background-image: url('<?php echo $this->thumb($src, 65, 45.5); ?>');"></div>
                            <?php endfor; ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="files">
                <?php
                $files = $at->fetchAllByPostId($post->getId());
                foreach ($files as $file) {
                    if ($file->getType() != 'image') {
                        ?>

                        <div class="attachment">
                            <a target="_blank" download="" href="<?php echo $this->uploadfilemanager->getFilePath($file->getUploadId()); ?>"><div class="icon-icon">
                                </div></a>
                            <div class="label"><a target="_blank" download="" href="<?php echo $this->uploadfilemanager->getFilePath($file->getUploadId()); ?>">
                                    <p><?= $this->uploadfilemanager->getFilename($file->getUploadId()); ?></p>

                                </a></div>
                        </div>


                        <?php
                    }
                }
                ?>
            </div>


        </div>

        <div class="post-replies">
            <div class="left">
                <div class="comments" onclick="window.location.href = '/post/details/<?= $post->getId(); ?>?scroll=down'">
                    <div class="commtent-icon"></div>
                    <div class="commtent-count"><?= $this->commentTable->countComments($post->getId()); ?></div>
                </div>
            </div>
            <div class="right">
                <?php
                $ft = $sm->get('favorite_table');
                $favor = $ft->getByUserIdAndPostId($post->getId(), $loggedInUser->user_id);
                ?>

                <div class="favorite <?php echo (!$favor) ? : 'active'; ?>" data-post-id="<?php echo $post->getId(); ?>"></div>
                <div class="divide">|</div>

                <?php
                $likeTable = $sm->get('like_table');
                $like = $likeTable->getByUserIdAndPostId($post->getId(), $loggedInUser->user_id);
                ?>

                <div class="likes" data-post-id="<?php echo $post->getId(); ?>">
                    <div class="like-icon <?php echo (!$like) ? : 'active'; ?>"></div>
                    <div class="count like-count <?php echo (!$like) ? : 'firm_blue'; ?>"><?= $this->likeTable->countLikes($post->getId()); ?></div>
                </div>
                <div class="likes like" ></div>
            </div>
        </div>
    </div>
</div>



<div class="post-comments">

    <?php foreach ($this->post_comments as $comment) { ?>

        <?php
        //
        $commentUserData = $this->getUserData($comment->getUserId());
        $commentUser = $sm->get('users_table')->getUserById($comment->getUserId());
        //
        ?>
        <div class="post-comment">
            <div class="comment-avatar"><a href="/post/list/<?= $commentUser->user_id; ?>">
                    <div style="background-image: url('<?php echo $commentUserData->getAvatarUrl(); ?>');">
                    </div>
                </a></div>
            <div class="comment-body">

                <div class="wrap">
                    <div class="comment-author">
                        <a href="/post/list/<?= $commentUser->user_id; ?>">
                            <?= $this->escapeHtml($commentUser->display_name); ?>
                        </a>
                    </div>

                    <div class="comment-date">
                        <?php
                        $formatedCommentDate = date_format(new DateTime($comment->getDate()), 'd.m.y H:i');
                        ?>
                        <?= $formatedCommentDate; ?>
                    </div>

                </div>

                <div class="comment-text">
                    <?= $this->escapeHtml($comment->getText()); ?>
                </div>
                <!--<div class="dele" data-id="<?= $comment->getId() ?>"> Удалить комментарий!</div>-->
            </div>

        </div>
    <?php } ?>


    <div class="post-comments-input">
        <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url(
                        'comment', array(
                    'action' => 'save',
                    'id' => $this->post->getId(),
                        )
        ));
        echo $this->form()->openTag($form);
        ?>
        <?php
        echo $this->formLabel($form->get('text'));
        echo $this->formElement($form->get('text'));
        echo $this->formElementErrors($form->get('text'));
        ?>

        <?php
        echo $this->formElement($form->get('submit'));
        echo $this->formElementErrors($form->get('submit'));
        ?>

        <?php echo $this->formHidden($form->get('post_id')); ?>
        <?php echo $this->formHidden($form->get('user_id')); ?>

        <?php echo $this->form()->closeTag() ?>
    </div>
</div>


<script>
    $(document).ready(function() {
        $('.dele').on('click', function() {
            var row = $(this).parent();
            var id = $(this).data("id");
            var cc = $('.comments_count');
            $.ajax({
                type: "POST",
                url: "/comment/delete",
                data: {"id": id, 'post_id': <?= $this->post->getId() ?>},
                cache: false,
                success: function(response) {
                    if (response && response.status === 'ok') {
                        row.remove();
                        cc.text(response.countComments)
                    }
                }
            });
        });

        $('.refresh').on('click', function() {
            var date_now = $(this).parents('.item').find('.post-create-date').data('date');
            var id = $(this).parents('.item').data('id');
            var date = $(this).parents('.item').find('.post-create-date');
            if (date.text() !== date_now) {

                $.ajax({
                    type: "POST",
                    url: "/post/refresh",
                    data: {"id": id},
                    cache: false,
                    success: function(response) {
                        if (response && response.status === 'ok') {
                            date.text('');
                            setTimeout(function() {
                                date.text(response.date)
                            }, 500);

                        }
                    }
                });
            } else {
            }
        });

    });
</script>

<script>
    $(document).ready(function() {
        $('.delete').on('click', function() {

            var item = $(this).parents('.item');

            var id = $(this).data('post-id');

            if (confirm("Вы действительно хотите удалить этот пост?")) {
                $.ajax({
                    type: "POST",
                    url: "/post/delete",
                    data: {"id": id},
                    cache: false,
                    success: function(response) {
                        if (response && response.status === 'ok') {
                            document.location.href = "/post/list/" + response.userid;
                        }
                    }
                });
            }
        });
    });
</script>

<script>
    $(document).ready(function() {
        $('.likes').on('click', function() {

            var id = $(this).data('post-id');
            var lc = $(this).children('.like-count');
            var li = $(this).children('.like-icon');

            $.ajax({
                type: "POST",
                url: "/like/like",
                data: {"id": id},
                cache: false,
                success: function(response) {
                    if (response && response.status === 'ok') {
                        lc.text(response.countLikes);
                        if (response.value == 0) {
                            li.removeClass('active');
                            lc.removeClass('firm_blue');
                        } else {
                            li.addClass('active');
                            lc.addClass('firm_blue');
                        }
                    } else {
                        document.location.href = "/users/register";
                    }
                }
            });
        });
    });
</script>

<script>
    $(document).ready(function() {
        $('.favorite').on('click', function() {

            var id = $(this).data('post-id');
            var fv_div = $(this);

            $.ajax({
                type: "POST",
                url: "/favorite/favorite",
                data: {"id": id},
                cache: false,
                success: function(response) {
                    if (response && response.status === 'ok') {

                        if (response.value == 0) {
                            fv_div.addClass('active');
                        } else {
                            fv_div.removeClass('active');
                        }
                    } else {
                        document.location.href = "/users/register";
                    }
                }
            });
        });
    });
</script>

<script>
    $(document).ready(function() {
        $('.small_img').on('click', function() {
            $(this).parent().parent().children('.big_img').click();

        });
    });
</script>


<?php $this->headScript()->appendFile($this->basePath()."/js/jquery.tosrus.min.all.js", 'text/javascript');?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/jquery.tosrus.all.css');?>


<div id="links">
</div>

<script>
    $(document).ready(function() {
        $('.big_img').on('click', function() {
            $('#links').empty();
            var links = $("#links");
            links.append($('<a></a>').attr('href', $(this).data('src').replace('url(', '').replace(')', '')));
            $(this).parent().children('.small_imgs').children().each(function(index) {
                links.append($('<a></a>').attr('href', $(this).data('src')));
            });

            $("#links a").tosrus({
                pagination: {
                    add: true,
                    type: "thumbnails"
                }
            });
            $('#links a:first').click();
        });

        $(window).load(function() {
            var param = getUrlParameter('scroll');

            if (param === 'down') {
                $("html, body").animate({scrollTop: $(document).height()}, 0);
            }
        });


        function getUrlParameter(sParam) {
            var sPageURL = window.location.search.substring(1);
            var sURLVariables = sPageURL.split('&');
            for (var i = 0; i < sURLVariables.length; i++)
            {
                var sParameterName = sURLVariables[i].split('=');
                if (sParameterName[0] == sParam)
                {
                    return sParameterName[1];
                }
            }
        }
    });
</script>
