<?php $sm = $this->getServiceManager(); ?>

<div class="posts search-result" data-order="ASC" data-view="">
    <?php if (count($posts)) : ?>

        <?php foreach ($posts as $post) { ?>
            <div class="search-result-item" onclick="window.location.href = '/post/view/<?= $post->get('id') ?>'" style="cursor: pointer;">
                <?php
                //Image
                $src = '/img/358x238_none.jpg';
                ?>
                <div class="author">
                    <div class="">
                        <a href="/post/search/?user=<?php echo $post->get('userId'); ?>">userId = <?php echo $post->get('userId'); ?></a>
                    </div>
                </div>

                <div class="post-id">
                    postId = <?php echo $post->get('id'); ?>
                </div>

                <div class="post-image">
                    <div class="small_image" style="background-image: url('<?= $this->thumb($src, 60, 45); ?>'); background-size: cover; "></div>
                    <div class="large_image" style="background-image: url('<?= $this->thumb($src, 120, 90); ?>'); background-size: cover; "></div>
                </div>

                <div class="post-title">
                    <?= $this->escapeHtml($post->get('title')) ?>
                </div>        

                <div class="post-text">
                    <?= $this->escapeHtml($post->get('text')); ?>
                </div>

                <div class="search_date_price_chaffer">
                    <div class="price"><?= $this->escapeHtml($post->get('price')) . " у.е." ?></div>
                    <div class="public"><?php if ($post->get('public')) echo "опубликовано"; ?></div>
                    <div class="create-date"><?= $post->get('createDate'); ?></div>
                </div>  

            </div>
        <?php } ?>

    <?php else : ?> 

        <div class="search-not-found"><?php echo $this->translate('Sorry, your search did not match, please try again.'); ?></div>

    <?php endif; ?>

</div>

