<?php $sm = $this->getServiceManager(); ?>

<div class="posts search-result" data-order="ASC" data-view="">
    <?php if (count($posts)) : ?>

        <?php foreach ($posts as $post) : ?>
           
            <?php echo $this->postExcerptViewWidget($post->get('post_id')); ?> 
    
        <?php endforeach; ?>

    <?php else : ?> 

        <div class="search-not-found"><?php echo $this->translate('Sorry, your search did not match, please try again.'); ?></div>

    <?php endif; ?>

</div>

