<?php
/**
 * Умная обрезка строки
 * @param string $str - исходная строка
 * @param int $lenght - желаемая длина результирующей строки
 * @param string $end - завершение длинной строки
 * @param string $charset - кодировка
 * @param string $token - символ усечения
 * @return string - обрезанная строка
 */
function cutStr($str, $lenght = 100, $end = '&nbsp;&hellip;', $charset = 'UTF-8', $token = '~')
{
    $str = strip_tags($str);
    if (mb_strlen($str, $charset) >= $lenght) {
        $wrap = wordwrap($str, $lenght, $token);
        $str_cut = mb_substr($wrap, 0, mb_strpos($wrap, $token, 0, $charset), $charset);
        return $str_cut .= $end;
    } else {
        return $str;
    }
}
?>
<?php
//
$sm = $this->getServiceManager();
//$user = $this->idenity();
?>

<section class="tape">
    <?php if ($posts->count()) { ?>
        <?php foreach ($this->posts as $post) { ?>

            <?php
            $userId = $post->getUserId();
            $postLink = "/post/details/$post->id";

            $author = $sm->get('users_table')->getUserById($post->user_id);
            $at = $sm->get('attachment_table');
            $files = $at->fetchAllByPostId($post->getId());
            $images = $at->getImagesByPostId($post->getId());

            $cityLocation = \Catalog\Data\Location::getLocationNameById($post->city);

            $postCreateDate = $post->getCreateDate();
            $postDate = new DateTime($postCreateDate);
            $formatedPostDate = date_format($postDate, 'd.m.y H:i');

            $postChaffer = ($post->chaffer) ? 'Договорная ' : '';
            ?>

            <div class="single-post item" data-id ="<?= $post->getId() ?>">

                <div class="post-avatar"><a href="/post/list/<?= $author->user_id; ?>">
                        <?php
                        $avatar_url = $this->getUserData($userId)->getAvatarUrl();
                        $postUserData = $this->getUserData($post->user_id);
                        ?>
                        <div style="background-image: url(<?php echo $avatar_url; ?>);"></div>

                    </a></div>

                <div class="post-actions">
                    <?php $loggedInUser = $sm->get('logged_in_user'); ?>
                    <?php if (isset($loggedInUser->user_id)) : ?>

                        <?php if ($loggedInUser->user_id == $post->getUserId()) : ?>
                            <div class="edit" onclick="window.document.location = '/post/edit/<?php echo $post->getId(); ?>'"></div>
                            <div class="divide">|</div>
                            <div class="refresh"></div>
                            <div class="divide">|</div>
                            <div class="delete" data-post-id="<?php echo $post->getId(); ?>"></div>
                        <?php else : ?>
                            <div class="chat" onclick="window.document.location = '/dialog/open/<?php echo $post->getUserId(); ?>'"></div>
                        <?php endif; ?>

                    <?php endif; ?>
                </div>

                <div class="post-body">

                    <div class="post-auhtor">
                        <a href="/post/list/<?= $author->user_id; ?>">
                            <?php echo $author->display_name; ?>
                        </a>

                    </div>

                    <div class="wrap">
                        <div class="post-location">
                            <?php echo $cityLocation; ?>

                        </div>
                        <div class="post-create-date">
                            <?php echo $formatedPostDate; ?>
                        </div>
                        <div class="post-chaffer">
                            <?php echo $postChaffer; ?>
                        </div>
                        <div class="post-price firm_red">
                            <?php echo isset($post->price) ? $this->escapeHtml($post->price) . ' у.е.' : ''; ?> 
                        </div>
                    </div>

                    <div class="wrap">
                        <div class="post-title"><a href="/post/details/<?= $post->getId(); ?>"><p><?= $this->escapeHtml($post->getTitle()); ?></p></a></div>
                    </div>


                    <div class="post-text"><a href="/post/details/<?= $post->getId(); ?>">
                            <?php
                            $postText = $post->getText();
                            $encode = mb_detect_encoding($postText);
                            $length = 300;
                            if (mb_strlen($postText) > $length) {

                                if ($encode == 'ASCII') {
                                    $subStrPostText = cutStr($postText, $length / 2);
                                } else {
                                    $subStrPostText = cutStr($postText, $length);
                                }

                                echo $subStrPostText . "<a href='$postLink'><span class='firm_blue'> полностью</span></a>";
                            } else {
                                echo $this->escapeHtml($postText);
                            }
                            ?>
                        </a></div>
                    <div class="wrap-images">
                        <div class="images">
                            <?php
                            $imagesCount = $images->count();
                            $imagesArray = $images->toArray();
                            ?>

                            <?php if ($imagesCount == 0) : ?>
                                <div class="big_img" data-src="/img/358x238_none.jpg" style="background-image: url('/img/358x238_none.jpg'); border: 1px solid #dbdbdb;"></div>
                            <?php endif; ?>

                            <?php if ($imagesCount > 0) : $src = $this->uploadfilemanager->getFilePath($imagesArray[0]['upload_id']); ?>
                                <div class="big_img" data-src="<?php echo $src; ?>" style="background-image: url('<?php echo $this->thumb($src, 358, 238); ?>')"></div>
                            <?php endif; ?>

                            <?php if ($imagesCount > 1) : ?>
                                <div class="small_imgs">
                                    <?php for ($i = 1; $i < $imagesCount; $i++) : $src = $this->uploadfilemanager->getFilePath($imagesArray[$i]['upload_id']); ?>
                                        <div class="small_img" data-src="<?php echo $src; ?>" style="background-image: url('<?php echo $this->thumb($src, 65, 45.5); ?>');"></div>
                                    <?php endfor; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="post-replies">
                    <div class="left">
                        <div class="comments" onclick="window.location.href = '/post/details/<?= $post->getId(); ?>?scroll=down'">
                            <div class="commtent-icon"></div>
                            <div class="commtent-count"><?= $this->commentTable->countComments($post->getId()); ?></div>
                        </div>
                    </div>
                    <div class="right">
                        <?php
                        $ft = $sm->get('favorite_table');
                        $favor = $ft->getByUserIdAndPostId($post->getId(), $loggedInUser->user_id);
                        ?>

                        <div class="favorite <?php echo (!$favor) ? : 'active'; ?>" data-post-id="<?php echo $post->getId(); ?>"></div>
                        <div class="divide">|</div>

                        <?php
                        $likeTable = $sm->get('like_table');
                        $like = $likeTable->getByUserIdAndPostId($post->getId(), $loggedInUser->user_id);
                        ?>

                        <div class="likes" data-post-id="<?php echo $post->getId(); ?>">
                            <div class="like-icon <?php echo (!$like) ? : 'active'; ?>"></div>
                            <div class="count like-count <?php echo (!$like) ? : 'firm_blue'; ?>"><?= $this->likeTable->countLikes($post->getId()); ?></div>
                        </div>
                        <div class="likes like" ></div>
                    </div>
                </div>
            </div>


        <?php } ?>

    <?php } else { ?>
        <div class="no-posts-favorites-dialogs">В ленте пока нет объявлений</div>
    <?php }
    ?>
</section>

<script>
    $(document).ready(function() {
        $('.delete').on('click', function() {

            var item = $(this).parents('.item');

            var id = $(this).data('post-id');

            if (confirm("Вы действительно хотите удалить этот пост?")) {
                $.ajax({
                    type: "POST",
                    url: "/post/delete",
                    data: {"id": id},
                    cache: false,
                    success: function(response) {
                        if (response && response.status === 'ok') {
                            item.remove();
                        }
                    }
                });
            }
        });

        $('.refresh').on('click', function() {
            var date_now = $(this).parents('.item').find('.post-create-date').data('date');
            var id = $(this).parents('.item').data('id');
            var date = $(this).parents('.item').find('.post-create-date');
            if (date.text() !== date_now) {

                $.ajax({
                    type: "POST",
                    url: "/post/refresh",
                    data: {"id": id},
                    cache: false,
                    success: function(response) {
                        if (response && response.status === 'ok') {
                            date.text('');
                            setTimeout(function() {
                                date.text(response.date)
                            }, 500)

                        }
                    }
                });
            } else {
            }
        });
    });
</script>

<script>
    $(document).ready(function() {
        $('.likes').on('click', function() {

            var id = $(this).data('post-id');
            var lc = $(this).children('.like-count');
            var li = $(this).children('.like-icon');

            $.ajax({
                type: "POST",
                url: "/like/like",
                data: {"id": id},
                cache: false,
                success: function(response) {
                    if (response && response.status === 'ok') {
                        lc.text(response.countLikes);
                        if (response.value == 0) {
                            li.removeClass('active');
                            lc.removeClass('firm_blue');
                        } else {
                            li.addClass('active');
                            lc.addClass('firm_blue');
                        }
                    } else {
                        document.location.href = "/users/register";
                    }
                }
            });
        });
    });
</script>

<script>
    $(document).ready(function() {
        $('.favorite').on('click', function() {

            var id = $(this).data('post-id');
            var fv_div = $(this);

            $.ajax({
                type: "POST",
                url: "/favorite/favorite",
                data: {"id": id},
                cache: false,
                success: function(response) {
                    if (response && response.status === 'ok') {

                        if (response.value == 0) {
                            fv_div.addClass('active');
                        } else {
                            fv_div.removeClass('active');
                        }
                    } else {
                        document.location.href = "/users/register";
                    }
                }
            });
        });
    });
</script>


<script>
    $(document).ready(function() {
        $('.small_img').on('click', function() {
            $(this).parents('.single-post').find('.big_img').click();
        });
    });
</script>

<?php $this->headScript()->appendFile($this->basePath()."/js/jquery.tosrus.min.all.js", 'text/javascript');?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/jquery.tosrus.all.css');?>


<div id="links">
</div>

<script>
    $(document).ready(function() {
        $('.big_img').on('click', function() {
            $('#links').empty();
            var links = $("#links");
            links.append($('<a></a>').attr('href', $(this).data('src')));

            $(this).parents('.single-post').find('.small_imgs').children().each(function(index) {
                links.append($('<a></a>').attr('href', $(this).data('src')));
            });
            $("#links a").tosrus({
                pagination: {
                    add: true,
                    type: "thumbnails"
                },
            });
            $('#links a:first').click();
        });
    });
</script>
