<section class="user-manager">
    <h2> User Manager </h2>
    <table style="width: 100%;">
        <tr>
            <th>id</th>
            <th>Name</th>
            <th>User ID/Email</th>
            <th>Actions</th>
        </tr>
        <?php
        $users = $this->users;
        foreach ($users as $user):
            ?>
            <tr>
                <td><?php echo $this->escapeHtml($user->getId()); ?></td>
                <td><?php echo $this->escapeHtml($user->getUsername()); ?></td>
                <td><?php echo $this->escapeHtml($user->getEmail()); ?></td>
                <td>
                    <a href="<?php echo $this->url('users/user-manager', array('action' => 'edit', 'id' => $user->getId()));
            ?>">Edit</a> | 

                    <a href="<?php echo $this->url('users/user-manager', array('action' => 'delete', 'id' => $user->getId()));
            ?>" onclick="return confirm('Are you sure?')">Delete</a>
                </td>
            </tr>

        <?php endforeach; ?>
    </table>

</section>