Action "edit", controller "Realty", module "Realty".
<?php
?>

<div class="widget">

    <div class="widget-title">edit realty widget <?php echo $realtyId; ?></div>

    <div class="widget-body">

        <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', "/realty/process/$realtyId");
        ?>

        <?php echo $this->form()->openTag($form); ?>
        <div class="form-list">
            <?php foreach ($form as $element) : ?>
                <div class="<?php echo 'block-' . $element->getName(); ?>">
                    <div class="label"><?php echo $this->formLabel($element); ?></div>
                    <div class="error"><?php echo $this->formElementErrors($element); ?></div>
                    <div class="field"><?php echo $this->formElement($element); ?></div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php echo $this->form()->closeTag() ?>


    </div>

</div>