<?php

use Banners\Model\Banner;

$sm = $this->getServiceManager();
$user = $sm->get('logged_in_user');
$bannersTable = $sm->get('banners_table');
$simpleBanner = $bannersTable->getBannerByTypeForUser(Banner::SIMPLE_BANNER, $user->getId());
$saleBanner = $bannersTable->getBannerByTypeForUser(Banner::SALE_BANNER, $user->getId());
$logoBanner = $bannersTable->getBannerByTypeForUser(Banner::LOGO_BANNER, $user->getId());
$vipBanner = $bannersTable->getBannerByTypeForUser(Banner::VIP_BANNER, $user->getId());
?>

<table class="b1<?php echo !empty($simpleBanner->image) ? ' set' : ''?>" cellpadding="0" cellspacing="0" onclick="window.location='/banners/simple/add'">
    <tr>
        <td></td>
    </tr>
</table>

<table class="b2<?php echo !empty($saleBanner->image) ? ' set' : ''?>" cellpadding="0" cellspacing="0" onclick="window.location='/banners/sale/add'">
    <tr>
        <td></td>
    </tr>
</table>

<table class="b3<?php echo !empty($logoBanner->image) ? ' set' : ''?>" cellpadding="0" cellspacing="0" onclick="window.location='/banners/logo/add'">
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>

<table class="b4<?php echo !empty($vipBanner->image) ? ' set' : ''?>" cellpadding="0" cellspacing="0" onclick="window.location='/banners/vip/add'">
    <tr>
        <td></td>
    </tr>
    <tr>
        <td></td>
    </tr>
</table>

<table class="text" cellpadding="0" cellspacing="0">
    <tr>
        <td class="default-desc_" style=""><p>Описание по умолчанию<p></td>
    </tr>
    <tr>
        <td class="simple-desc" style="display: none;"><p>simple Идет прекрастный пояснительный текст, в котором вы можете узнать о возможностях размещения своей рекламы в баннерах<p></td>
    </tr>
    <tr>
        <td class="sale-desc" style="display: none;"><p> sale Идет прекрастный пояснительный текст, в котором вы можете узнать о возможностях размещения своей рекламы в баннерах<p></td>
    </tr>
    <tr>
        <td class="logo-desc" style="display: none;"><p> logo Идет прекрастный пояснительный текст, в котором вы можете узнать о возможностях размещения своей рекламы в баннерах<p></td>
    </tr>
    <tr>
        <td class="vip-desc" style="display: none;"><p> vipИдет прекрастный пояснительный текст, в котором вы можете узнать о возможностях размещения своей рекламы в баннерах<p></td>
    </tr>
</table>

<script>
    $(document).ready(function() {

        $('.b1').on('mouseenter', function(e) {
            $('.simple-desc').show();
        });
        $('.b1').on('mouseleave', function(e) {
            $('.simple-desc').hide();
        });

        $('.b2').on('mouseenter', function(e) {
            $('.sale-desc').show();
        });
        $('.b2').on('mouseleave', function(e) {
            $('.sale-desc').hide();
        });

        $('.b3').on('mouseenter', function(e) {
            $('.logo-desc').show();
        });
        $('.b3').on('mouseleave', function(e) {
            $('.logo-desc').hide();
        });

        $('.b4').on('mouseenter', function(e) {
            $('.vip-desc').show();
        });
        $('.b4').on('mouseleave', function(e) {
            $('.vip-desc').hide();
        });
    });
</script>
