<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <title>title</title>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
                ->prependStylesheet($this->basePath() . '/css/reset.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
        ?>
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/jquery.cookie.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',));
        ?>

        <!--<link href='http://fonts.googleapis.com/css?family=Open+Sans&subset=latin,cyrillic' rel='stylesheet' type='text/css'>-->

    </head>
    <body class="<?php echo $this->controllerName(); ?>">

        <div class="wrap-header">
            <div class="header">

                <div class="logo"><a href="/">home</a></div>
                <div class="search">
                    <?php echo $this->searchFormWidget(); ?>
                </div>
                <div class="menu">
                    <ul>
                        <li> <a href="/user/info">user</a></li>
                        <li> <a href="/post/list">post</a></li>
                        <li><a href="/post/add">post+</a></li>
                        <li><a href="/category/list">categ.</a></li>
                        <li> <a href="/upload">upload</a></li>
                        <li><a href="/dialog">dialog</a></li>
                    </ul>
                    
                </div>
            </div>
        </div>

        <div class="wrap-body">
            <div class="body">
                <div class="wrap-menu">

                </div>
                <div class="wrap-content">
                    <div class="content">
                        <?php echo $this->content; ?>
                    </div>
                </div> 
                <div class="wrap-sidebar">
                    <div class="sidebar"></div>
                </div>
            </div>
        </div>

        <div class="wrap-footer">
            <div class="footer"></div>
        </div>

        <?php echo $this->inlineScript() ?>

        <script>
            $(document).ready(function() {
                $('.widget-title').on('click', function() {

                    $(this).parent().children('.widget-body').toggle(100);

                })
            });
        </script>
    </body>
</html>
