<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <title>title</title>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
                ->prependStylesheet($this->basePath() . '/css/reset.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
        ?>
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/jquery.cookie.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',));
        ?>
    </head>
    <body class="<?php echo $this->controllerName(); ?>">

        <div class="wrap-header">
            <div class="header">
                <div class="logo"></div>
                <div class="search"></div>
            </div>
        </div>

        <div style="clear:both;"></div>

        <div class="wrap-body">
            <div class="body">
                <div class="wrap-menu">
                    <div class="menu"></div>
                </div>
                <div class="wrap-content">
                    <div class="content"></div>
                </div> 
                <div class="wrap-sidebar">
                    <div class="sidebar"></div>
                </div>
            </div>
        </div>

        <div style="clear:both;"></div>
        
        <div class="wrap-footer">
            <div class="footer"></div>
        </div>
    </body>
</html>
