<table>
    <tr>
        <td colspan="3">
            <h2 style="margin-top: 49px;">Приветствуем вас на информационном ресурсе www.ardfo.by</h2>
        </td>
    </tr>
    <tr>
        <td colspan="3">
            <p style="margin-top: 61px;">Пожалуйста, выберите форму регистрации</p>
        </td>
    </tr>
    <tr>
        <td><a class="button" href="<?= $this->url('users/register', array('action' => 'legal')); ?>"> Юридическое лицо </a></td>
        <td><a class="button" href="<?= $this->url('users/register', array('action' => 'individual')); ?>"> Индивидуальный предприниматель </a></td>
        <td><a class="button" href="<?= $this->url('users/register', array('action' => 'physical')); ?>"> Физическое лицо </a></td>
    </tr>
    <tr>
        <td><a class="adv" href="#">преимущества</a></td>
        <td><a class="adv" href="#">преимущества</a></td>
        <td><a class="adv" href="#">преимущества</a></td>
    </tr>

</table>