<?php if ($this->error) : ?>
    <?php if ($this->message) : ?>
        <p class="error"><?php echo $this->message; ?></p>
    <?php endif; ?>
<?php endif ?>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL, array(
            'controller' => 'register',
            'action' => 'individual-process',
        ))
);
?>

<?= $this->form()->openTag($form); ?>

<h3>Регистрационные данные</h3>
<dl>
    <dt><?= $this->formLabel($form->get('email')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('email')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('email')); ?></span>
    </dd>

    <dt><?= $this->formLabel($form->get('password')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('password')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('password')); ?></span>
    </dd>
</dl>

<h3>Контактные данные</h3>
<dl>
    <dt><?= $this->formLabel($form->get('org_name')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('org_name')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('org_name')); ?></span>
    </dd>
    
    <dt><?= $this->formLabel($form->get('last_name')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('last_name')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('last_name')); ?></span>
    </dd>

    <dt><?= $this->formLabel($form->get('first_name')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('first_name')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('first_name')); ?></span>
    </dd>

    <dt><?= $this->formLabel($form->get('middle_name')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('middle_name')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('middle_name')); ?></span>
    </dd>

    <dt><?= $this->formLabel($form->get('country')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('country')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('country')); ?></span>
    </dd>

    <dt><?= $this->formLabel($form->get('region')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('region')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('region')); ?></span>
    </dd>

    <dt><?= $this->formLabel($form->get('city')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('city')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('city')); ?></span>
    </dd>

    <dt><?= $this->formLabel($form->get('zip')); ?></dt>
    <dd> 
        <?= $this->formElement($form->get('zip')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('zip')); ?></span>
    </dd>

    <dt><?= $this->formLabel($form->get('street')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('street')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('street')); ?></span>
    </dd>

    <dt><?= $this->formLabel($form->get('house')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('house')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('house')); ?></span>
    </dd>

    <dt><?= $this->formLabel($form->get('office')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('office')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('office')); ?></span>
    </dd>

    <dt><?= $this->formLabel($form->get('phone')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('phone')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('phone')); ?></span>
    </dd>
</dl>

<h3>Регистрационная форма в ЕГР (сведения из св-ва о регистрации)</h3>

<dl>
    <dt><?= $this->formLabel($form->get('unp')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('unp')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('unp')); ?></span>
    </dd>

    <dt><?= $this->formLabel($form->get('egr_org')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('egr_org')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('egr_org')); ?></span>
    </dd>
    <dt><?= $this->formLabel($form->get('egr_num')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('egr_num')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('egr_num')); ?></span>
    </dd>

    <dt><?= $this->formLabel($form->get('egr_date')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('egr_date')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('egr_date')); ?></span>
    </dd>
</dl>
<h3>Банковские реквизиты</h3>

<dl>
    <dt><?= $this->formLabel($form->get('bank')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('bank')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('bank')); ?></span>
    </dd>

    <dt><?= $this->formLabel($form->get('bank_code')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('bank_code')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('bank_code')); ?></span>
    </dd>
    <dt><?= $this->formLabel($form->get('bank_address')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('bank_address')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('bank_address')); ?></span>
    </dd>

    <dt><?= $this->formLabel($form->get('bank_acc')); ?></dt>
    <dd>
        <?= $this->formElement($form->get('bank_acc')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('bank_acc')); ?></span>
    </dd>

    <dd class="figlet_captcha">
        <?= $this->formCaptcha($form->get('captcha')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('captcha')); ?></span>
    </dd>

    <dt>При нажатии на кнопку <span style="font-weight: bold;">Регистрация</span> Вы подтверждаете, что прочитали и согласны с <a href="/page/view/agreement" target="_blank" style="color: #009cff;">Пользовательским соглашением</a>.</dt>
    <dd></dd>

    <dt>&nbsp;</dt>
    <dd>
        <?= $this->formElement($form->get('submit')); ?>
        <span class="errors"><?= $this->formElementErrors($form->get('submit')); ?></span>
    </dd>
</dl>


<?= $this->form()->closeTag(); ?>

<script type="text/javascript">

    $(document).ready(function() {
        /**********************************************************************/
        var catalog = '';
        getCatalog();
        function getCatalog() {
            var data = new FormData();
            $.ajax({
                type: "post",
                url: '/search/filter/ajax-catalog',
                data: data,
                cache: false,
                processData: false,
                contentType: false,
                success: function(response) {
                    if (response && response.status === 'ok') {
                        catalog = response.catalog;
                        return catalog;
                    }
                }
            });
        }
        /**********************************************************************/

        $('select[name="country"]').on('focus', function() {
            $('select[name="region"]').empty();
            setCountrySelect();
        });


        $('select[name="country"]').on('change', function() {
            $('select[name="region"]').empty();
            setRegionSelect();
        })

        $('select[name="region"]').on('change', function() {
            $('select[name="city"]').empty();
            setCitySelect();
        })




        function setCountrySelect() {
            $('select[name="country"]').empty();
            $('select[name="region"]').empty();
            $('select[name="city"]').empty();
            $('select[name="country"]').append($('<option data-id="-1">'));

            catalog.forEach(function(entry) {
                if (entry.parent_id === 0) {
                    var option = $('<option>' + entry.name + '</option>');
                    option.attr('data-id', entry.id);
                    option.attr('value', entry.id);
                    $('select[name="country"]').append(option);
                }
            });
        }

        function setRegionSelect() {
            $('select[name="region"]').empty();
            $('select[name="city"]').empty();
            $('select[name="region"]').append($('<option data-id="-1">'));

            var countryId = $('select[name="country"] option:selected').attr('data-id');
            if (countryId !== -1) {

                catalog.forEach(function(entry) {
                    if (entry.parent_id == countryId) {
                        var option = $('<option>' + entry.name + '</option>');
                        option.attr('data-id', entry.id);
                        option.attr('value', entry.id);
                        $('select[name="region"]').append(option);
                    }
                });
            }
        }

        function setCitySelect() {
            $('select[name="city"]').empty();
            $('select[name="city"]').append($('<option data-id="-1">'));

            var regionId = $('select[name="region"] option:selected').attr('data-id');
            if (regionId !== -1) {

                catalog.forEach(function(entry) {
                    if (entry.parent_id == regionId) {
                        var option = $('<option>' + entry.name + '</option>');
                        option.attr('data-id', entry.id);
                        option.attr('value', entry.id);
                        $('select[name="city"]').append(option);
                    }
                });
            }
        }

    });
</script>