<h2> New User Registration </h2>
<?php if ($this->error) : ?>
    <?php if ($this->message) : ?>
        <p class="error"><?php echo $this->message; ?></p>
    <?php endif; ?>
<?php endif ?>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL, array(
            'controller' => 'register',
            'action' => 'process',
        ))
);
//$form->setAttribute('method','post'); //?? 
echo $this->form()->openTag($form);
?>

<dl class="register-form">
    <dt><?php echo $this->formLabel($form->get('username')); ?></dt>
    <dd>
        <?php
        echo $this->formElement($form->get('username'));
        echo $this->formElementErrors($form->get('username'));
        ?>
    </dd>
    <dt><?php echo $this->formLabel($form->get('email')); ?></dt>
    <dd>
        <?php
        echo $this->formElement($form->get('email'));
        echo $this->formElementErrors($form->get('email'));
        ?>
    </dd>
    <dt><?php echo $this->formLabel($form->get('password')); ?></dt>
    <dd>
        <?php
        echo $this->formElement($form->get('password'));
        echo $this->formElementErrors($form->get('password'));
        ?>
    </dd>
    <dt><?php echo $this->formLabel($form->get('confirm_password')); ?></dt>
    <dd>
        <?php
        echo $this->formElement($form->get('confirm_password'));
        echo $this->formElementErrors($form->get('confirm_password'));
        ?>
    </dd>
    <dt>&nbsp;</dt>
    <dd>
        <?php
        echo $this->formElement($form->get('submit'));
        echo $this->formElementErrors($form->get('submit'));
        ?>
    </dd>
</dl>

<?php echo $this->form()->closeTag(); ?>

<a href = "/"> << Back to Home </a>
