<?php

use Banners\Model\Banner;

$sm = $this->getServiceManager();
$user = $sm->get('logged_in_user');
$bannersTable = $sm->get('banners_table');
$banners = $bannersTable->getBannersByTypeForUser(Banner::LOGO_BANNER, $user->getId());
?>

<div id="content">
    <div class="top_line"></div>
    
    <?php echo 'Logo banners list'; ?>
    <a href="/banners/logo/add">add</a>
    <table cellpadding="0" cellspacing="0">
        <tr>
            <th>id</th>
            <th>user_id</th>
            <th>image_id</th>
            <th>type</th>
            <th>url</th>
            <th>title</th>
            <th>cost</th>
            <th>sale</th>
            <th>create_date</th> 
            <th>off_date</th> 
            <th>is_on</th> 
        </tr>
        <?php foreach ($banners as $banner) : ?> 
            <tr>
                <td><?= $banner->id ?></td>
                <td><?= $banner->user_id ?></td>
                <td><?= $banner->image_id ?></td>
                <td><?= $banner->type ?></td>
                <td><?= $banner->url ?></td>
                <td><?= $banner->title ?></td>
                <td><?= $banner->cost ?></td>
                <td><?= $banner->sale ?></td>
                <td><?= $banner->create_date ?></td>
                <td><?= $banner->off_date ?></td>
                <td><?= $banner->is_on ?></td>
            </tr>
        <?php endforeach; ?>
    </table>

</div>

<style>
    table, td, th {
        border: 1px solid seagreen;
        padding: 5px;
    }
    th {
        font-weight: bold;
    }
</style>