<form class="search-user-panel" method="GET" action="/users/activate/control" enctype="multipart/form-data">
    <span>Введите УНП организации</span>
    <input name="unp" required type="number" class="unp" value=""/>
    <input type="submit" value="Найти" class="unp-submit blue-button"/>
    <span><a class="firm_blue" href="/users/activate/control?unp=<?= $unp ?>">Обновить страницу</a></span>
</form>

<div class="search-user-result">
    <?php if (isset($users)) : ?>

        <?php foreach ($users as $user) : ?>


            <div class="user-info">
                <a href="/post/list/<?= $user->user_id ?>"><?= $user->email ?></a> |
                УНП: <?php echo $user->unp; ?> | 
                <?php
                if ($user->reg_type == 1) {
                    echo '<span style="color: red;">Физ:</span> ' . $user->last_name . ' ' . $user->first_name . ' ' . $user->middle_name . ' | ';
                }
                ?>
                <?php
                if ($user->reg_type == 3) {
                    echo 'Орг: ' . $user->org_name . ' | ';
                }
                ?>
                <?php
                if ($user->reg_type == 2) {
                    echo 'ИнП: ' . $user->last_name . ' ' . $user->first_name . ' ' . $user->middle_name . ' | ';
                }
                ?>

                cтатус: 
                <?php if ($user->state == \Users\Model\User::STATE_NOT_ACTIVATED) : ?>
                                <!-- <a href="/users/activate/control?unp=<?= $unp ?>&id=<?= $user->user_id ?>&state=on" class="state-not-active">Не активен</a> -->
                    <span class="state-not-active">Не активен</span>
                <?php else /* if ($user->state == \Users\Model\User::STATE_ACTIVATED) */ : ?>
                    <!-- <a href="/users/activate/control?unp=<?= $unp ?>&id=<?= $user->user_id ?>&state=off" class="state-active">Активен</a> -->
                    <span class="state-active">Активен</span>

                <?php endif; ?>

                <br/>Активен до: <a class="reduce" href="/users/activate/control?unp=<?= $unp ?>&id=<?= $user->user_id ?>&term=reduce">(-)</a> 
                <?= $formatedCommentDate = date_format(new DateTime($user->off_date), 'd.m.y H:i'); ?> 
                <a class="increase" href="/users/activate/control?unp=<?= $unp ?>&id=<?= $user->user_id ?>&term=increase">(+)</a>


            </div>

        <?php endforeach; ?>

        <?php if ($users->count() == 0) : ?>

            <div class="user-not-found">Пользователь с УНП "<?= $unp ?>" не найден</div>

        <?php endif; ?>

    <?php endif; ?>
</div>



<style>
    .search-user-panel {
        width: 800px;
        height: 40px;
        font-family: 'Courier New';
    }
    .search-user-panel * {
        display: inline-block;
        line-height: 23px;
        margin: 5px;
    }
    .search-user-result {
        width: 800px;
        margin: 5px;
        font-family: 'Courier New';
    }
    .user-info {
        margin: 0px 0px 20px 0px;
    }
    .user-info a {
        color: #009cff;
    }
    .user-info a:hover {
        text-decoration: underline;
    }
    .user-info .state-active,  .user-info .increase {
        color: #5CB85C;
    }
    .user-info .state-not-active,  .user-info .reduce {
        color: #FF0000;
    }
</style>

<script>
    $(document).ready(function() {

    });
</script>