<div class="activate-text">
    <p>
        Уважаемый пользователь.<br/>
        <br/>
        Вы находитесь  в одном шаге от завершения регистрации на www.ardfo.by<br/>
        <br/>
        В целях активации Вашего аккаунта на www.ardfo.by, пожалуйста,<br/> 
        произведите платеж в течение 3 (три) рабочих дней. <br/>
        В случае не поступления платежа на расчетный счет ООО «АРДФО», <br/>
        Ваши регистрационные данные будут удалены из системы.<br/>
        <br/>
        <br/>
        На E-mail, указанный Вами при регистрации, высланы банковские реквизиты ООО «АРДФО»
    </p>
</div>

<style>
    .users-module.activate #vip-ads {
        display: block;
    }
    .users-module.activate #content {
        width: 645px;
    }
    .users-module.activate #content .top_line {
        width: 645px;
    }
    .activate-text {
        text-align: center;
        font-size: 14px;
        line-height: 16px;
        margin-top: 83px; 
    }
</style>