<?php $sm = $this->getServiceManager(); ?>

<form name="search-form" action="/post/search/">
    <input name="query" type="text" placeholder="Что искать?">
    <input type="button" value="Найти" onclick="submit()">
</form>

<div class="search-result" data-order="ASC" data-view="">
    <?php if (count($searchResults)) : ?>

            <?php foreach ($searchResults as $searchResult) { ?>
                <div class="search-result-item" onclick="window.location.href = '/post/details/<?= $searchResult->id ?>'" style="cursor: pointer;">
                    <?php
                    //Image
                    $src = '/img/358x238_none.jpg';

                    ?>

                    <div class="search_img">
                        <div class="small_image" style="background-image: url('<?= $this->thumb($src, 60, 45); ?>'); background-size: cover; "></div>
                        <div class="large_image" style="background-image: url('<?= $this->thumb($src, 120, 90); ?>'); background-size: cover; "></div>
                    </div>

                    <div class="search_title_text">
                        <div class="search-title"><?= $this->escapeHtml($searchResult->title) ?></div>
                        <div class="search-text"><?= $this->escapeHtml($searchResult->text); ?></div>
                    </div>        

                    <div class="search_date_price_chaffer">
                        <div class="search_price"><?= $this->escapeHtml($searchResult->price) . " у.е." ?></div>
                        <div class="search_chaffer"><?php if ($searchResult->chaffer) echo "Договорная"; ?></div>
                        <div class="search_date"><?= $searchResult->create_date ?></div>
                    </div>  

                </div>
            <?php } ?>

    <?php else : ?> 

        <div class="search-not-found"><?php echo $this->translate('Sorry, your search did not match, please try again.'); ?></div>

    <?php endif; ?>

</div>

