
<a href="/upload/add">add</a>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>User_id</th>
                <th>name</th>
                <th>path</th>
                <th>url</th>
                <th>link</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->uploads as $upload) { ?>

                <tr>
                    <td class="text"><?= $upload->get('id'); ?></td>
                    <td><?= $upload->get('userId'); ?></td>
                    <td><?= $upload->get('name'); ?></td>
                    <td><?= $upload->get('path'); ?></td>
                    <td><?= $upload->get('url'); ?></td>
                    <td>
                        <div class="">
                            <a href="<?= $upload->get('url'); ?>"><?= $upload->get('name'); ?></a>
                        </div>
                    </td>
                    <td class="del" data-id="<?= $upload->get('id'); ?>" 
                        data-full_filename="<?= $upload->get('path'); ?>">Delete ajax<br/>
                        <a href="/upload/delete/<?= $upload->get('id'); ?>">Delete</a>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>


<script>
    $(document).ready(function() {
        $('.del').on('click', function() {
            var row = $(this).parent();
            var id = $(this).parent().children('.del').data("id");
            var full_filename = $(this).parent().children('.del').data("full_filename");
            $.ajax({
                type: "POST",
                url: "/upload/delete",
                data: {"id": id, "full_filename": full_filename},
                cache: false,
                success: function(response) {
                    if (response && response.status === 'ok') {
                        row.remove();
                    }
                }
            });
        });
    });
</script>