<?php
$sm = $this->getServiceManager();
$userTable = $sm->get('user_table');
$loggedInUserId = $sm->get('logged_in_user_id');
//echo $loggedInUserId;
$user = $userTable->getUserById($loggedInUserId);
//echo json_encode($user->getArrayCopy());
//echo $user->get('email');
?>
<a href="/user/login">login</a><br/>
<a href="/user/register">register</a><br/>
<a href="/user/logout">logout</a><br/>


<?php if (isset($user)) : ?> 
    <?php echo "you logged in as: " . $user->get(\User\Model\User::DISPLAY_NAME); ?>
<?php endif; ?>